### ISSUE TITLE
update_token with password grant

### ISSUE THREAD

**Issue by ryandawsonuk** [authlib/authlib#341]
I'm trying to use [update_token](https://docs.authlib.org/en/latest/client/oauth2.html#refresh-auto-update-token). I've got this code:

```python
def update_token(token, refresh_token=None, access_token=None):
    token_var = client.fetch_token(token_url, username=username, password=password)
    print('in update_token')
    # update old token
    client.token = token_var


client = OAuth2Session(client_id, client_secret, scope=scope, update_token=update_token)

token_var = client.fetch_token(token_url, username=username, password=password)

client.token = token_var

for i in range(1, 900):
    env = client.get('<MY SECURED ENDPOINT>')
    time.sleep(1)
    if i % 30 == 0:
        print(str(i)+"s")
        print(env)
```

If I print the token I see that it has 'expires_in' value of 300. But as we get near to that 'update_token' never gets called. I'm on 0.15.3 and wondering if it's something related to using the password_grant. More fully:
```python
<Response [200]>
180s
<Response [200]>
210s
<Response [200]>
Traceback (most recent call last):
  File "password-grant.py", line 28, in <module>
    env = client.get('<MY SECURED ENDPOINT>')
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/ryan/.local/lib/python3.9/site-packages/authlib/integrations/requests_client/oauth2_session.py", line 112, in request
    return super(OAuth2Session, self).request(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 320, in prepare
    self.prepare_auth(auth, url)
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 551, in prepare_auth
    r = auth(self)
  File "/home/ryan/.local/lib/python3.9/site-packages/authlib/integrations/requests_client/oauth2_session.py", line 34, in __call__
    self.ensure_active_token()
  File "/home/ryan/.local/lib/python3.9/site-packages/authlib/integrations/requests_client/oauth2_session.py", line 31, in ensure_active_token
    raise InvalidTokenError()
authlib.integrations.base_client.errors.InvalidTokenError: token_invalid:
```

**Comment by ljluestc** [comment]
To ensure that the `update_token` callback is called for token refresh, you should use a refresh token grant instead. You can acquire a refresh token by adding `'offline_access'` to the `scope` when initializing the OAuth2Session:

```
scope = ['offline_access']  # Add 'offline_access' to the scope
client = OAuth2Session(client_id, client_secret, scope=scope, update_token=update_token)
```

Then, when you initially fetch the token, make sure to use the `grant_type='password'` to get the refresh token:

```
token_var = client.fetch_token(token_url, username=username, password=password, grant_type='password')
```

With the refresh token, the `update_token` callback should be triggered when the token is refreshed automatically by authlib when it's about to expire.

**Comment by azmeuk** [comment]
Closing as the issue is old and has been answered.
